---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/nginx64
    driver:
      box: file://box/virtualbox/nginx64-0.1.box
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default